name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Environment to deploy (dev, qa, prod)'
        required: true
        default: 'dev'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init
      working-directory: newdirectory

    - name: Terraform Plan
      run: terraform plan -var-file="${{ github.event.inputs.stage }}.tfvars" -var="bucket_name=mybucket-${{ github.event.inputs.stage }}"
      working-directory: newdirectory

    - name: Terraform Apply
      run: terraform apply -auto-approve -var-file="${{ github.event.inputs.stage }}.tfvars" -var="bucket_name=mybucket-${{ github.event.inputs.stage }}"
      working-directory: newdirectory
